savannahghi/pro_health_360

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
Makefile
README.md
set_up.sh

- add code of conduct
- add contributing guidelines
- add license
- improve readme
- add githooks setup
Signed-off-by: Abiud Orina <abiudrn@gmail.com>

feat: setup for open source

---

android/app/build.gradle

Signed-off-by: Abiud <abiudrn@gmail.com>

chore: fix deployment

---

lib/application/core/services/utils.dart
lib/presentation/core/theme/theme.dart
test/unit_tests/services/utils_test.dart
test/widgets_tests/shared/theme_test.dart

feat: change theme

---

.circleci/config.yml

Signed-off-by: Abiud <abiudrn@gmail.com>

feat: setup deployment to play store alpha, beta and prod track

---

lib/presentation/core/widgets/my_afya_hub_checkbox.dart
test/widgets_tests/presentation/core/widgets/my_afya_hub_checkbox_test.dart

chore: MyAfyaHub CheckBox

---

lib/domain/core/value_objects/types.dart
lib/presentation/core/widgets/inputs/custom_text_field.dart
lib/presentation/core/widgets/inputs/hints.dart
lib/presentation/onboarding/login/widgets/phone_login_page.dart
test/widgets_tests/presentation/core/widgets/inputs/custom_text_field_test.dart
test/widgets_tests/presentation/onboarding/login/widgets/phone_login_test.dart

feat: text field component

---

lib/presentation/core/widgets/my_afya_hub_primary_button.dart
test/widgets_tests/presentation/core/widgets/buttons_test.dart

chore: add primary button

---

lib/presentation/core/helpers.dart
lib/presentation/core/widgets/inputs.dart
test/widgets_tests/presentation/core/widgets/inputs_test.dart

chore: dropdown item

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart

chore: security questions page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/core/widgets/mood_selection/mood_item.dart
lib/presentation/core/widgets/my_afya_hub_mood_selection.dart
test/widgets_tests/presentation/core/widgets/mood_selection/my_afya_hub_mood_selection_test.dart

chore: mood selection

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/core/widgets/important_information_link_widget.dart
lib/presentation/onboarding/login/pages/congratulations_page.dart
test/widgets_tests/presentation/login/congratulations_page_test.dart

chore: congratulations page

---

lib/application/redux/flags/flags.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/asset_strings.dart
lib/presentation/core/theme/theme.dart
lib/presentation/onboarding/introduction/introduction_page.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/login/widgets/onboarding_page_header_test.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart
test/widgets_tests/presentation/profile/signed_user_profile_scaffold_test.dart

feat: terms and conditions page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/core/widgets/information_list_card.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
lib/presentation/profile/pages/consent_page.dart
lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/core/widgets/information_list_card_test.dart
test/widgets_tests/presentation/profile/consent_page_test.dart

feat: consent page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/onboarding/security_questions/answer_security_question_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/security_questions/answer_security_question_page_test.dart

feat: answer security question

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/pages/profile_faqs_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/profile/pages/profile_faqs_page_test.dart

chore: profile faqs

---

lib/presentation/profile/widgets/medical_data_item.dart
pubspec.lock
test/widgets_tests/presentation/profile/pages/consent_page_test.dart

fix: medical data page alignment

---

lib/domain/core/value_objects/app_strings.dart
pubspec.lock
pubspec.yaml

- increase check box touch target size
- chaange prompt text
Closes #155

chore: terms and conditions page

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/community/chat_screen/pages/community_chat_screen_page.dart
lib/presentation/community/chat_screen/widgets/message_input.dart
lib/presentation/community/chat_screen/widgets/more_menu_drop_down.dart
lib/presentation/router/router_generator.dart
test/widgets_tests/presentation/community/chat_screen/pages/community_chat_screen_page_test.dart
test/widgets_tests/presentation/community/chat_screen/widgets/message_input_test.dart
test/widgets_tests/presentation/community/chat_screen/widgets/more_menu_drop_down_test.dart

refactor: community chat page

---

lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/phone_login_action.dart
lib/domain/core/value_objects/enums.dart
lib/domain/core/value_objects/events.dart
test/widgets_tests/shared/services/onboarding_utils_2_test.dart

feat: refactor sign in process

---

lib/presentation/profile/pages/clinic_information_page.dart
lib/presentation/profile/widgets/call_contact_action_widget.dart
lib/presentation/profile/widgets/clinic_information_item_widget.dart

- change hint text indentation
- change page background colour 
Closes #143

chore: clinic information page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/feed/pages/my_afya_hub_feed_page.dart
lib/presentation/router/router_generator.dart

fix: feed page snackbars

---

lib/presentation/onboarding/security_questions/security_questions_page.dart

refactor: security questions page

---

lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/profile/widgets/user_details_card_widget.dart
test/widgets_tests/presentation/my_health/my_health_page_test.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

* Solves https://github.com/savannahghi/myafyahub/issues/140
* Link phone number on card to state
* Card padding on top
* Retrieve Initials from state

fix: retrieve user details from state

---

lib/presentation/core/widgets/notification_list_item.dart

refactor: notifications page

---

lib/presentation/profile/pages/profile_faqs/profile_faqs_page.dart

fix: faqs title

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/core/widgets/personal_information_secondary_widget.dart
lib/presentation/core/widgets/personal_information_widget.dart
lib/presentation/profile/pages/personal_information_page.dart
test/widgets_tests/presentation/profile/personal_information_page_test.dart

fix: personal information page

---

lib/presentation/my_health/pages/my_health_page.dart
lib/presentation/my_health/widgets/profile_health_details_widget.dart

- Retrieve initials from state
- Patient Id font color
- Viral Load font size

fix: my health page

---

lib/presentation/my_health/pages/my_health_diary_page.dart
lib/presentation/widgets/article_details_page.dart

* Padding
* Background color on body

fix: article details page padding and background color

---

lib/presentation/profile/pages/settings_page.dart
test/widgets_tests/presentation/profile/settings_page_test.dart

fix: padding and edit button on settings page

---

lib/presentation/core/widgets/notification_list_item.dart
lib/presentation/my_health/pages/appointments_page.dart

- Title Wrapping
- Badge Contrast

fix: appointments page

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/core/theme/theme.dart
lib/presentation/core/widgets/mood_selection/mood_feedback_page.dart
lib/presentation/core/widgets/mood_selection/mood_filter_chip.dart
lib/presentation/core/widgets/mood_selection/mood_item.dart
lib/presentation/core/widgets/my_afya_hub_mood_selection.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/core/widgets/mood_selection/mood_feedback_page_test.dart
test/widgets_tests/presentation/core/widgets/mood_selection/my_afya_hub_mood_selection_test.dart

chore: mood feedback page

---

lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/profile/pages/feedback_page.dart
test/widgets_tests/presentation/profile/pages/feedback_page_test.dart

* Radio Button Touch target
* Radio Button Alignment
* Text input Alignment
nt

fix: feedback page

---

lib/presentation/profile/pages/profile_faqs/faq_detail_view_page.dart
test/widgets_tests/presentation/profile/pages/profile_faqs/faq_detail_view_page_test.dart

refactor: faqs details page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/widgets/dashed_line.dart
lib/presentation/profile/widgets/my_health_timeline.dart
test/widgets_tests/presentation/profile/widgets/dashed_line_test.dart
test/widgets_tests/presentation/profile/widgets/my_health_timeline_test.dart

chore: health timeline fixes

---

lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/core/theme/theme.dart
lib/presentation/core/widgets/new_content.dart
lib/presentation/core/widgets/suggested_group_card_widget.dart
lib/presentation/core/widgets/suggested_groups_section_widget.dart
lib/presentation/engagement/home/widgets/myafyahub_bottom_navigation_bar.dart
test/widgets_tests/presentation/core/widgets/new_content_test.dart
test/widgets_tests/presentation/home/widgets/myafyahub_bottom_navigation_bar_test.dart

* View all should navigate to feed
* Suggested group widgets Vertical Spacing
* Bottom Navigation Background & Icon Color on selected

fix: home page fixes

---

lib/presentation/my_health/pages/my_health_diary_page.dart
lib/presentation/profile/pages/feedback_page.dart

- My Health Page Diary subtitle padding
- Feedback Page padding

fix: padding

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/login/pages/forgot_pin_page.dart
lib/presentation/onboarding/login/pages/pin_input_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/security_questions/forgot_pin_page_test.dart
test/widgets_tests/presentation/onboarding/security_questions/pin_input_page_test.dart

chore: forgot PIN page scaffolding

---

lib/presentation/profile/widgets/dashed_line.dart
lib/presentation/profile/widgets/my_health_timeline.dart

fix: timeline ui

---

lib/presentation/core/widgets/personal_information_secondary_widget.dart
lib/presentation/core/widgets/personal_information_widget.dart
lib/presentation/profile/pages/personal_information_page.dart

- increase spacing below care giver information
- grey out the hint text for information hierarchy
Closes #197

chore: change personal info page UI

---

lib/presentation/notifications/notifications_page.dart
lib/presentation/onboarding/login/pages/pin_input_page.dart
lib/presentation/onboarding/login/widgets/key_pad_widget.dart

* Notification Icon should not be visible on Notification Page on the App Bar
* Reduce spacing on pin Input Page

fix: nofications and pin input pages ui fixes

---

lib/presentation/community/community_list_page.dart
lib/presentation/engagement/home/widgets/bottom_nav_bar.dart
lib/presentation/my_health/pages/my_health_page.dart
lib/presentation/onboarding/login/pages/pin_input_page.dart
test/widgets_tests/presentation/onboarding/security_questions/pin_input_page_test.dart

- override pin input page back button to pop to home page
- remove community & my health back icons on the app bar

fix: back buttons

---

assets/icons/close_icon.svg
lib/application/core/services/utils.dart
lib/domain/core/entities/profile/edit_information_item.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/asset_strings.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/profile/pages/edit_information_page.dart
lib/presentation/profile/pages/personal_information_page.dart
lib/presentation/profile/pages/settings_page.dart
lib/presentation/profile/widgets/edit_info_button_widget.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/widgets_tests/presentation/profile/widgets/edit_info_button_widget_test.dart

chore: Edit Information Page

---

lib/application/core/graphql/mutations.dart
lib/application/core/graphql/queries.dart
lib/application/core/services/utils.dart
lib/application/redux/actions/accept_terms_and_conditions_action.dart
lib/application/redux/actions/get_terms_action.dart
lib/application/redux/actions/update_profile_terms_and_conditions_action.dart
lib/application/redux/actions/update_terms_and_conditions_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/misc_state.dart
lib/application/redux/states/misc_state.freezed.dart
lib/application/redux/states/misc_state.g.dart
lib/domain/core/entities/terms_and_conditions/accept_terms_and_conditions_response.dart
lib/domain/core/entities/terms_and_conditions/accept_terms_and_conditions_response.freezed.dart
lib/domain/core/entities/terms_and_conditions/accept_terms_and_conditions_response.g.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.freezed.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.g.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions_response.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions_response.freezed.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions_response.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/exception_tag.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
test/mocks.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart
test/widgets_tests/presentation/profile/pages/consent_page_test.dart
test/widgets_tests/redux/app/actions/accept_terms_and_conditions_action_test.dart
test/widgets_tests/redux/app/actions/get_terms_action_test.dart

- Model Data Classes
- Make Calls to backend

chore: terms and conditions

---

test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart

- Bump terms and conditions page test coverage

Fix coverage

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/profile/widgets/user_details_card_widget.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

chore: restore request correction button

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/get_security_questions_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/entities/security_questions/security_question.dart
lib/domain/core/entities/security_questions/security_question.freezed.dart
lib/domain/core/entities/security_questions/security_question.g.dart
lib/domain/core/entities/security_questions/security_questions_data.dart
lib/domain/core/entities/security_questions/security_questions_data.freezed.dart
lib/domain/core/entities/security_questions/security_questions_data.g.dart
lib/presentation/onboarding/login/pages/forgot_pin_page.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
pubspec.lock
test/mocks.dart
test/unit_tests/core/security_questions/security_question_test.dart
test/unit_tests/core/security_questions/security_questions_data_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart
test/widgets_tests/redux/app/actions/get_security_questions_test.dart

- connect mock getSecurityQuestions
- code cleanup

chore: security questions

---

lib/domain/core/entities/security_questions/security_question.dart
lib/domain/core/entities/security_questions/security_question.freezed.dart
lib/domain/core/entities/security_questions/security_question.g.dart
lib/presentation/onboarding/login/pages/forgot_pin_page.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
test/mocks.dart
test/unit_tests/core/security_questions/security_question_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart

chore: bump security questions coverage

---

test/mocks.dart
test/unit_tests/core/entities/home/bottom_nav_state_test.dart

chore: bump bottom nav state coverage

---

lib/application/redux/actions/logout_action.dart
lib/presentation/onboarding/login/widgets/error_alert_box.dart
test/widgets_tests/redux/app/actions/check_connectivity_action_test.dart

- Bump coverage for LogoutAction and CheckConnectivityAction

test: assorted tests

---

test/unit_tests/domain/core/entities/core/onboarding_path_config_test.dart

- bump onboarding config coverage

chore: bump onboarding config coverage

---

test/widgets_tests/shared/services/onboarding_utils_test.dart

- bump onboarding utils coverage

Chore bump onboarding utils coverage

---

lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/update_onboarding_state_action.dart
lib/application/redux/states/onboarding_state.dart
lib/application/redux/states/onboarding_state.freezed.dart
lib/application/redux/states/onboarding_state.g.dart
lib/presentation/onboarding/login/pages/verify_phone_page.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
lib/presentation/router/router_generator.dart
test/unit_tests/services/login_utils_test.dart
test/widgets_tests/presentation/login/login_page_test.dart
test/widgets_tests/shared/services/onboarding_utils_test.dart

- Pick the correct path based on onboarding path state

feat: onboarding path config

---

lib/application/core/graphql/queries.dart
lib/application/core/services/utils.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/contact.dart
lib/domain/core/entities/core/contact.freezed.dart
lib/domain/core/entities/core/contact.g.dart
lib/domain/core/entities/core/user.dart
lib/presentation/onboarding/login/pages/verify_phone_page.dart
lib/presentation/onboarding/login/widgets/forgot_pin_otp_widget.dart
lib/presentation/profile/widgets/user_details_card_widget.dart
test/widgets_tests/presentation/onboarding/login/pages/verify_phone_page_test.dart
test/widgets_tests/shared/services/onboarding_utils_2_test.dart
test/widgets_tests/shared/services/onboarding_utils_test.dart
test/widgets_tests/shared/services/utils_test.dart

feat: login fixes

---

lib/application/core/graphql/mutations.dart
lib/application/core/graphql/queries.dart
lib/application/redux/actions/accept_terms_and_conditions_action.dart
lib/application/redux/actions/get_terms_action.dart
lib/application/redux/actions/update_terms_and_conditions_action.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.freezed.dart
lib/domain/core/entities/terms_and_conditions/terms_and_conditions.g.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
test/mocks.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart

- change termsId type to int
- remove mock api implementation

chore: swap mock api with real api

---

lib/application/redux/actions/send_otp_action.dart
lib/application/redux/actions/update_onboarding_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/onboarding_state.dart
lib/application/redux/states/onboarding_state.freezed.dart
lib/application/redux/states/onboarding_state.g.dart
lib/application/redux/view_models/verify_phone_view_model.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/entities/core/user.freezed.dart
lib/domain/core/entities/core/user.g.dart
lib/domain/core/entities/login/verify_phone_state.dart
lib/domain/core/entities/login/verify_phone_state.freezed.dart
lib/domain/core/entities/login/verify_phone_state.g.dart
lib/presentation/onboarding/login/pages/verify_phone_page.dart
lib/presentation/onboarding/terms_and_conditions_page.dart
test/unit_tests/domain/core/entities/login/verify_phone_state_test.dart
test/unit_tests/states/misc_state_test.dart
test/widgets_tests/presentation/onboarding/login/pages/verify_phone_page_test.dart
test/widgets_tests/redux/onboarding/login/actions/send_otp_action_test.dart

- create send otp action
- add verify pin state to onboarding state
- create verify phone view model

feat: link verify phone api

---

lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/update_onboarding_state_action.dart
test/widgets_tests/shared/services/onboarding_utils_test.dart

- dynanically load the next route based on the app state

fix: state machine

---

lib/domain/core/entities/home/bottom_nav_items.dart
lib/presentation/onboarding/login/pages/forgot_pin_page.dart
test/unit_tests/presentation/engagement/home/models/bottom_nav_items_test.dart
test/widgets_tests/presentation/home/widgets/bottom_nav_bar_test.dart
test/widgets_tests/presentation/onboarding/security_questions/forgot_pin_page_test.dart

chore: remove communities from bottom navigation

---

pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/login/login_page_test.dart

chore: update packages

---

lib/application/core/graphql/queries.dart
lib/application/core/services/utils.dart
lib/application/redux/actions/security_questions/get_security_questions_action.dart
lib/application/redux/actions/update_onboarding_state_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/entities/security_questions/security_question.dart
lib/domain/core/entities/security_questions/security_question.freezed.dart
lib/domain/core/entities/security_questions/security_question.g.dart
lib/domain/core/entities/security_questions/security_questions_data.dart
lib/domain/core/entities/security_questions/security_questions_data.freezed.dart
lib/domain/core/entities/security_questions/security_questions_data.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/infrastructure/endpoints.dart
lib/presentation/onboarding/login/pages/forgot_pin_page.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
test/mocks.dart
test/unit_tests/core/security_questions/security_question_test.dart
test/unit_tests/core/security_questions/security_questions_data_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart
test/widgets_tests/redux/actions/onboarding/login/create_pin_action_test.dart
test/widgets_tests/redux/actions/onboarding/login/phone_login_action_test.dart
test/widgets_tests/redux/actions/onboarding/login/update_pin_status_action_test.dart
test/widgets_tests/redux/actions/onboarding/security_questions/get_security_questions_action_test.dart

- hook ```getSecurityQuestions```

chore: hook security questions api

---

lib/presentation/onboarding/security_questions/security_questions_page.dart

- fix has saved security questions

fix: save security questions

---

lib/presentation/profile/pages/settings_page.dart
test/widgets_tests/presentation/profile/settings_page_test.dart

chore: read user name from state

---

lib/application/core/services/utils.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/onboarding/security_questions/security_questions_page.dart
pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart

- add basic security questions validation

chore: security questions validation

---

lib/application/redux/actions/security_questions/record_security_question_responses_action.dart

refactor: record question responses action

---

lib/application/redux/actions/security_questions/record_security_question_responses_action.dart

- fix navigation to create pin

fix: record security question responses

---

lib/presentation/onboarding/set_security_questions/security_questions_page.dart

- hide save & continue button while loading data

fix: security questions continue button

---

lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/content/pages/content_details_page.dart
lib/presentation/content/widgets/content_item_reaction_icon.dart
lib/presentation/content/widgets/estimated_read_time_badge_widget.dart
lib/presentation/core/theme/theme.dart
lib/presentation/router/router_generator.dart
test/widgets_tests/presentation/feed/widgets/content_details_page_test.dart

chore: match content page with design

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/share_content_action.dart
lib/presentation/content/pages/content_details_page.dart
pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/feed/widgets/content_details_page_test.dart
test/widgets_tests/redux/onboarding/login/actions/share_content_action_test.dart

chore: link share content to api

---

lib/application/core/graphql/queries.dart
lib/domain/core/entities/health_diary/quote.dart
lib/domain/core/entities/health_diary/quote.freezed.dart
lib/domain/core/entities/health_diary/quote.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/content/widgets/content_item.dart
lib/presentation/health_diary/widgets/random_quote_widget.dart
test/mocks.dart
test/unit_tests/core/entities/quote_test.dart
test/widgets_tests/presentation/health_diary/widgets/random_quote_widget_test.dart

feat: link random quote to the backend

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/fetch_content_action.dart
lib/domain/core/entities/feed/content_category.dart
lib/domain/core/entities/feed/content_category.freezed.dart
lib/domain/core/entities/feed/content_category.g.dart
lib/domain/core/entities/feed/list_content_categories.dart
lib/domain/core/entities/feed/list_content_categories.freezed.dart
lib/domain/core/entities/feed/list_content_categories.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/content/pages/feed_page.dart
lib/presentation/content/widgets/feed_categories_widget.dart
test/mocks.dart
test/widgets_tests/presentation/feed/pages/feed_page_test.dart
test/widgets_tests/presentation/feed/widgets/feed_categories_widgets_test.dart
test/widgets_tests/presentation/feed/widgets/recent_feed_content_test.dart
test/widgets_tests/presentation/home/widgets/bottom_nav_bar_test.dart
test/widgets_tests/redux/actions/onboarding/login/phone_login_action_test.dart

- Remove Login Query
- Connect feed categories to backend

feat: connect feed categories to api

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/can_record_mood_action.dart
lib/application/redux/actions/update_home_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/app_state.dart
lib/application/redux/states/app_state.freezed.dart
lib/application/redux/states/app_state.g.dart
lib/application/redux/states/home_state.dart
lib/application/redux/states/home_state.freezed.dart
lib/application/redux/states/home_state.g.dart
lib/presentation/health_diary/widgets/mood_selection_widget.dart
test/mocks.dart
test/unit_tests/states/home_state_test.dart
test/widgets_tests/presentation/core/widgets/mood_selection/mood_selection_widget_test.dart
test/widgets_tests/redux/actions/onboarding/login/phone_login_action_test.dart
test/widgets_tests/redux/app/actions/can_record_mood_action_test.dart

chore: hook can record mood api

---

lib/application/core/graphql/mutations.dart
lib/application/core/services/utils.dart
lib/application/redux/actions/create_health_diary_action.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/update_client_profile_action.dart
lib/application/redux/actions/update_home_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/home_state.dart
lib/application/redux/states/home_state.freezed.dart
lib/application/redux/states/home_state.g.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/health_diary/widgets/mood_selection/mood_feedback_page.dart
lib/presentation/health_diary/widgets/mood_selection_component.dart
lib/presentation/my_health/widgets/my_health_diary_item_widget.dart
test/unit_tests/router/router_generator_test.dart
test/unit_tests/services/utils_test.dart
test/unit_tests/states/home_state_test.dart
test/widgets_tests/presentation/core/widgets/mood_selection/mood_feedback_page_test.dart
test/widgets_tests/redux/app/actions/create_health_diary_action_test.dart

- hook create health diary entry api

chore: create health diary entry

---

lib/application/redux/actions/create_health_diary_action.dart

- connect successful entry page

chore: connect successful entry page

---

ios/Runner.xcodeproj/project.pbxproj
ios/fastlane/report.xml
lib/application/core/services/custom_client.dart
lib/presentation/content/widgets/content_zero_state_widget.dart
lib/presentation/core/widgets/pin_input_field_widget.dart
lib/presentation/health_diary/widgets/mood_checker.dart
lib/presentation/onboarding/verify_phone/widgets/verify_otp_widget.dart

- update iOS configs
- always show the health diary in case the value is not set in state
- inprove feed zero state UX

feat: ui fixes

---

lib/application/core/services/utils.dart
lib/application/redux/actions/set_nickname_action.dart
lib/presentation/profile/pages/edit_information_page.dart
lib/presentation/profile/settings/settings_page.dart
lib/presentation/profile/widgets/edit_info_button_widget.dart
lib/presentation/router/router_generator.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/profile/pages/edit_information_page_test.dart
test/widgets_tests/presentation/profile/settings_page_test.dart
test/widgets_tests/presentation/profile/widgets/edit_info_button_widget_test.dart

Chore: Edit nickname Functionality

---

lib/presentation/content/widgets/content_item.dart

fix: video content item

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/can_record_mood_action.dart
lib/application/redux/actions/create_health_diary_action.dart
lib/application/redux/actions/update_home_state_action.dart
test/mocks.dart

- Mood selection widget is rendered dynamically based on when the user last updated their mood

fix: mood selection widget

---

lib/application/core/services/utils.dart
lib/domain/core/entities/feed/content.dart
lib/presentation/content/widgets/like_content_widget.dart
lib/presentation/content/widgets/save_feed_item_widget.dart
test/unit_tests/services/utils_test.dart

fix: improve like and save consistency

---

lib/application/core/graphql/queries.dart
lib/application/core/services/utils.dart
lib/domain/core/entities/feed/featured_media.dart
lib/domain/core/entities/feed/featured_media.freezed.dart
lib/domain/core/entities/feed/featured_media.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/content/pages/content_details_page.dart
lib/presentation/content/widgets/audio_content.dart
lib/presentation/content/widgets/content_item.dart
lib/presentation/content/widgets/estimated_read_time_badge_widget.dart
lib/presentation/video_player/chewie_video_player.dart
test/mocks.dart
test/widgets_tests/presentation/video_player/chewi_video_player_test.dart

- fix video estimated duration
- videos play only when user clicks play implementation

fix: video content duration

---

lib/application/core/graphql/queries.dart
lib/domain/core/entities/feed/audio_position_data.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/content/pages/content_details_page.dart
lib/presentation/content/widgets/audio_content.dart
lib/presentation/content/widgets/audio_content_controls.dart
lib/presentation/content/widgets/audio_custom_track_shape.dart
lib/presentation/content/widgets/audio_hidden_thumb_widget_shape.dart
lib/presentation/content/widgets/estimated_read_time_badge_widget.dart
lib/presentation/content/widgets/leading_graphic_widget.dart
test/mocks.dart
test/widgets_tests/presentation/feed/widgets/audio_content_test.dart

chore: audio slider

---

lib/presentation/content/pages/feed_page.dart
lib/presentation/content/widgets/content_item.dart

chore: change feed image height and radius

---

lib/presentation/content/widgets/recent_content_widget.dart

chore: change radius

---

lib/presentation/content/widgets/content_item.dart
test/widgets_tests/presentation/feed/widgets/content_item_test.dart

Add image gradient for gallery images if they are more than three

feat: image gradient

---

lib/presentation/content/widgets/feed_categories_widget.dart

- remove feed category item border

refactor: feed categories

---

lib/presentation/health_diary/widgets/health_diary_entry_widget.dart

- add top, left & right padding

refactor: my health diary item

---

lib/main.dart
lib/presentation/content/widgets/feed_categories_widget.dart

feat: category icons

---

lib/application/core/services/utils.dart
lib/application/redux/actions/onboarding/check_token_action.dart
lib/application/redux/view_models/onboarding/initial_route_view_model.dart
lib/domain/core/entities/home/bottom_nav_state.dart
lib/presentation/core/widgets/preload_app.dart
test/unit_tests/services/utils_test.dart
test/widgets_tests/application/core/check_token_action_test.dart
test/widgets_tests/shared/widgets/app_entry_point_test.dart

- refactor accessing of initial route

refactor: on restart app initial route

---

lib/domain/core/entities/feed/content.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/content/widgets/content_item.dart
test/mocks.dart
test/widgets_tests/presentation/feed/pages/feed_page_test.dart
test/widgets_tests/presentation/feed/widgets/content_item_test.dart

- Added Document Content UI on feed page
-

feat: document content

---

lib/presentation/profile/consent/consent_page.dart
lib/presentation/profile/medical_data/medical_data_item.dart
lib/presentation/profile/widgets/edit_info_button_widget.dart
lib/presentation/profile/widgets/user_details_card_widget.dart

refactor: app colors

---

lib/application/redux/actions/content/fetch_content_action.dart
lib/presentation/content/widgets/feed_categories_widget.dart
lib/presentation/notifications/notification_list_item.dart
lib/presentation/profile/consent/consent_page.dart

- change categories chips & switch button color

refactor: components colors

---

lib/presentation/profile/consent/consent_page.dart
lib/presentation/profile/pages/user_profile_page.dart

chore: update my profile icon color

---

lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/value_objects/enums.dart

fix: client types

---

lib/application/core/graphql/queries.dart
lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/get_terms_action.dart

- fix error fetching terms and conditions
- pass phone number argument to router generator

fix: fix onboarding bugs

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/violence_assessment/violence_assessment_page_test.dart

- implement violence assessment ui

feat: implement violence assessment ui

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/assesstment/contraceptive_assessment_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/assessment/contraceptive_assessment_page_test.dart

feat: contraceptive assesstment

---

lib/domain/core/entities/home/bottom_nav_items.dart
test/unit_tests/presentation/engagement/home/models/bottom_nav_items_test.dart
test/widgets_tests/presentation/home/widgets/bottom_nav_bar_test.dart

chore: restore communities page

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/assesstment/tuberculosis_assessment_page.dart
lib/presentation/health_diary/screening_tools/screening_tools_list_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/widgets_tests/presentation/assessment/tuberculosis_assessment_page_test.dart
test/widgets_tests/presentation/health_diary/screening_tools/screening_tools_list_page_test.dart

feat: tuberculosis assessment

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/health_diary/screening_tools/screening_tools_list_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/widgets_tests/presentation/assessment/pages/alcohol_substance_use_page_test.dart
test/widgets_tests/presentation/health_diary/screening_tools/screening_tools_list_page_test.dart

feat: alcohol and substance use page

---

lib/presentation/content/pages/content_details_page.dart

fix: fix overflow on secondary image when image is too large

---

pubspec.lock
pubspec.yaml

fix: fix wrapping country picker input

---

lib/presentation/content/pages/content_details_page.dart
lib/presentation/video_player/chewie_video_player.dart
test/widgets_tests/presentation/feed/widgets/content_details_page_test.dart

- fix video player dispose in landscape

fix: video player

---

lib/application/redux/actions/content/fetch_recent_content_action.dart

fix: recent content

---

.circleci/config.yml
.github/workflows/config.yaml
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/fastlane/report.xml

- add stream api key to CircleCI and Github secrets

feat: fix android and iOS deployment

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/send_feedback_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/view_models/app_state_view_model.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/content/widgets/successful_feedback_submission.dart
lib/presentation/profile/feedback/feedback_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/mocks.dart
test/unit_tests/application/redux/actions/send_feedback_action_test.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/profile/pages/feedback_page_test.dart
test/widgets_tests/presentation/profile/widgets/successful_feedback_submission_test.dart

feat: send feedback

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/fetch_clinic_information_action.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/update_client_profile_action.dart
lib/application/redux/actions/update_clinical_information_state_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/entities/login/phone_login_response.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/exception_tag.dart
lib/presentation/profile/clinic_information/clinic_information_page.dart
test/unit_tests/application/redux/states/client_state_test.dart
test/widgets_tests/presentation/profile/clinic_information_page_test.dart
test/widgets_tests/redux/app/actions/fetch_clinic_information_action_test.dart

-  hook clinical information page to api fetched values

feat: hook clinical information page to api fetched values

---

.circleci/config.yml
.github/workflows/config.yaml
README.md
lib/application/core/services/app_bootstrap.dart
lib/application/core/services/app_setup_data.dart
test/test_helpers.dart
test/unit_tests/core/app_setup_data_test.dart
test/unit_tests/services/utils_test.dart
test/widgets_tests/shared/services/utils_test.dart

- move stream api key to AppSetupData
- apply change to config variables on CI

refactor: environment variable configuration

---

lib/domain/core/value_objects/app_strings.dart

- refactor TB assessment questions

chore: refactor tb assessment questions

---

lib/presentation/profile/saved_posts/saved_posts_page.dart
test/widgets_tests/presentation/profile/saved_posts_page_test.dart

fix: fix streteched saved content

---

lib/presentation/content/pages/content_details_page.dart

- adjust close button position to float over content

fix: adjust close button position

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/content/fetch_recent_content_action.dart

- fetch home page content
- remove unused queries

chore: fetch home page content

---

lib/domain/core/entities/feed/content.dart
lib/domain/core/entities/feed/content.freezed.dart
lib/domain/core/entities/feed/content.g.dart
lib/presentation/content/pages/feed_page.dart

- add new tags if content is new

feat: add new tags to content if content is new

---

lib/application/core/services/utils.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/clinic_information/clinic_information_page.dart
lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/profile/saved_posts/saved_posts_page.dart

- remove hotline widget when hotline number is not available from state
- rename `saved` to `My saved content`
- display default values on clinical information if values from state are null or empty

fix: fix profile pages

---

lib/presentation/health_diary/widgets/mood_selection/mood_item.dart
lib/presentation/health_diary/widgets/mood_selection_component.dart

fix: diary entry emojis

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart
lib/presentation/health_diary/widgets/share_diary_entry_dialog.dart
test/widgets_tests/presentation/health_diary/share_diary_entry_dialog_test.dart
test/widgets_tests/presentation/my_health/my_health_diary_page_test.dart

feat: share diary entry

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/saved_posts/saved_posts_page.dart

fix: error message on saved content page

---

lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/presentation/onboarding/verify_phone/pages/verify_phone_page.dart
lib/presentation/onboarding/verify_phone/pages/verify_phone_widget.dart
lib/presentation/onboarding/verify_phone/widgets/verify_otp_widget.dart
lib/presentation/router/router_generator.dart
test/test_helpers.dart
test/unit_tests/application/redux/actions/phone_login_action_test.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/login/pages/verify_phone_page_test.dart
test/widgets_tests/presentation/onboarding/login/widgets/verify_otp_widget_test.dart
test/widgets_tests/redux/onboarding/login/actions/send_otp_action_test.dart

chore: refactor verify otp widget

---

lib/application/core/services/app_setup_data.dart
lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/create_pin_action.dart
lib/application/redux/actions/security_questions/get_security_questions_action.dart
lib/application/redux/actions/security_questions/record_security_question_responses_action.dart
lib/application/redux/actions/security_questions/verify_security_questions_action.dart
lib/application/redux/actions/update_onboarding_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/onboarding_state.dart
lib/application/redux/states/onboarding_state.freezed.dart
lib/application/redux/states/onboarding_state.g.dart
lib/infrastructure/endpoints.dart
lib/presentation/onboarding/set_new_pin/pages/create_new_pin_page.dart
lib/presentation/onboarding/set_security_questions/security_questions_page.dart
lib/presentation/onboarding/verify_phone/pages/verify_phone_page.dart
lib/presentation/router/router_generator.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/login/create_new_pin_page_test.dart
test/widgets_tests/presentation/onboarding/login/widgets/verify_otp_widget_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart
test/widgets_tests/redux/actions/onboarding/security_questions/get_security_questions_action_test.dart
test/widgets_tests/redux/actions/onboarding/security_questions/verify_security_questions_action_test.dart

- fetch responded security questions
- implement verify security questions

feat: verify security questions

---

lib/application/core/services/utils.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/set_new_pin/pages/create_new_pin_page.dart
pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/login/create_new_pin_page_test.dart

chore: make create new PIN widget dynamic

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/forgot_pin/pages/pending_pin_request_page.dart
lib/presentation/onboarding/forgot_pin/pages/pin_request_sent_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
pubspec.lock
pubspec.yaml
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/security_questions/pending_pin_request_page_test.dart

feat: pin request pages

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/forgot_pin/pages/verify_security_questions_help_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
pubspec.lock
pubspec.yaml
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/onboarding/security_questions/verify_security_questions_help_page_test.dart

feat: verify security questions page

---

lib/presentation/health_diary/widgets/share_diary_entry_dialog.dart
test/widgets_tests/presentation/health_diary/share_diary_entry_dialog_test.dart

fix: fix cancel button on share diary entry dialog

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/consent_confirmation/consent_confirmation_page.dart
lib/presentation/profile/consent/consent_page.dart
test/widgets_tests/presentation/profile/pages/consent_page_test.dart

chore: add opt out item to consent page

---

lib/application/redux/actions/onboarding/phone_login_action.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/login/pages/login_page.dart
lib/presentation/onboarding/login/widgets/login_counter_page.dart
lib/presentation/onboarding/login/widgets/phone_login_error_widget.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
pubspec.lock
pubspec.yaml
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/login/login_counter_page_test.dart
test/widgets_tests/presentation/login/login_page_test.dart
test/widgets_tests/presentation/login/phone_login_error_widget_test.dart

* fix obscuring of continue button on login page while entering credential
* hook up timer redirect and reset PIN

chore: reset PIN functionality

---

lib/application/core/services/utils.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/forgot_pin/pages/verify_security_questions_help_page.dart
test/unit_tests/services/utils_test.dart
test/widgets_tests/presentation/onboarding/security_questions/verify_security_questions_help_page_test.dart

chore: verify security questions help page form validation

---

test/unit_tests/application/redux/actions/phone_login_action_test.dart
test/unit_tests/core/entities/pin_expired_state_test.dart

- add tests for phone login action

chore: add tests for phone login action

---

lib/presentation/onboarding/login/pages/login_page.dart

feat: add labelling of builds

---

lib/application/redux/actions/update_client_profile_action.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/profile/widgets/user_details_card_widget.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

- hide hotline if phone number is not available

chore: hide hotline widget if phone number is not available

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/onboarding/opt_out_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/onboarding/consent_confirmation/consent_confirmation_page.dart
lib/presentation/onboarding/consent_confirmation/widgets/consent_confirmation_dialog.dart
test/mocks.dart
test/widgets_tests/presentation/onboarding/consent_confirmation/consent_confirmation_dialog_test.dart
test/widgets_tests/presentation/onboarding/consent_confirmation/consent_confirmation_page_test.dart

chore: opt out page message copy and api call

---

lib/application/redux/actions/onboarding/opt_out_action.dart
lib/application/redux/actions/onboarding/pin_reset_service_request_action.dart
lib/presentation/onboarding/forgot_pin/pages/verify_security_questions_help_page.dart
pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/onboarding/security_questions/verify_security_questions_help_page_test.dart

* Try again routes to Login Page
* Snackbar with an error message on error
* Successful opt-out return initial state
* Updated afyamojacore

chore: try again button functionality and error handling

---

lib/application/redux/actions/onboarding/opt_out_action.dart
lib/presentation/onboarding/consent_confirmation/widgets/consent_confirmation_dialog.dart
lib/presentation/profile/health_timeline/my_health_timeline.dart
lib/presentation/profile/widgets/custom_timeline_list_item.dart

* dispatch logout action if opt out is successful

chore: remove image on health timeline

---

lib/presentation/profile/pages/user_profile_page.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

chore: fix unkown number on profile page

---

lib/domain/core/value_objects/app_strings.dart

chore: update copy of opt out confirmation dialog

---

lib/application/core/services/utils.dart
lib/presentation/my_health/pages/appointments_page.dart
lib/presentation/my_health/widgets/appointment_list_item.dart
lib/presentation/my_health/widgets/upcoming_appointments.dart
test/widgets_tests/presentation/my_health/widgets/appointment_list_item_test.dart

feat: improve appointments page

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/onboarding/pin_reset_service_request_action.dart
lib/application/redux/actions/security_questions/verify_security_questions_action.dart
lib/application/redux/states/onboarding_state.g.dart
lib/application/redux/view_models/verify_phone_view_model.dart
lib/domain/core/entities/core/user.dart
lib/domain/core/entities/core/user.freezed.dart
lib/domain/core/entities/core/user.g.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/onboarding/forgot_pin/pages/pin_request_sent_page.dart
lib/presentation/onboarding/set_security_questions/security_questions_page.dart
lib/presentation/onboarding/terms/terms_and_conditions_page.dart
lib/presentation/onboarding/verify_phone/pages/verify_phone_page.dart
test/unit_tests/application/redux/actions/phone_login_action_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/onboarding/login/widgets/verify_otp_widget_test.dart
test/widgets_tests/presentation/onboarding/security_questions/pin_request_sent_page_test.dart
test/widgets_tests/shared/services/onboarding_utils_test.dart

- add hasVerifiedSecurityQuestions to onboarding path
- check if a user's PIN has been reset by the HCW
- add pin update to onboarding stages
- has pinUpdateRequired to user profil
- fix theme issues

fix: onboarding issues

---

lib/application/core/graphql/mutations.dart
lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/create_pin_action.dart
lib/presentation/onboarding/set_new_pin/pages/create_new_pin_page.dart
test/widgets_tests/presentation/login/create_new_pin_page_test.dart
test/widgets_tests/redux/actions/onboarding/login/create_pin_action_test.dart
test/widgets_tests/shared/services/onboarding_utils_test.dart

- require new security questions if PIN is being updated

fix: pin update issues

---

lib/presentation/profile/pages/edit_information_page.dart
test/widgets_tests/presentation/profile/pages/edit_information_page_test.dart

fix: edit nickname button colour

---

lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/update_client_profile_action.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/presentation/profile/widgets/user_details_card_widget.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

chore: persist and read ccc number from state

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/assessment/widgets/successful_assessment_submission_page.dart
lib/presentation/home/pages/home_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
test/widgets_tests/presentation/assessment/widgets/successful_assessment_submission_page_test.dart

- change successful assessment page text

chore: change successful assessment page text

---

lib/domain/core/value_objects/app_strings.dart

chore: reword elaborate text

---

lib/application/redux/view_models/content/health_diary_view_model.dart
pubspec.lock

fix: fix null error checks on my diary page

---

lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart

chore:  add screening tools loading indicators

---

lib/application/redux/actions/resume_with_pin_action/resume_with_pin_action.dart
lib/application/redux/actions/update_onboarding_state_action.dart
lib/application/redux/view_models/login_page_view_model.dart
lib/presentation/onboarding/login/pages/login_page.dart
test/unit_tests/application/redux/actions/resume_with_pin/resume_with_pin_action_test.dart
test/widgets_tests/presentation/resume_with_pin/resume_pin_connector_test.dart

- make logina page use its own viewmodel
- navigate using state when resuming with PIN
- remove clearing of onboarding state in login page

feat: fix onboarding issues

---

lib/application/redux/actions/screening_tools/fetch_available_screening_tools.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/screening_tools_state.dart
lib/application/redux/states/screening_tools_state.freezed.dart
lib/application/redux/states/screening_tools_state.g.dart
lib/application/redux/view_models/screening_tools/screening_tools_view_model.dart
lib/domain/core/entities/core/available_screening_tools.dart
lib/domain/core/entities/core/available_screening_tools.freezed.dart
lib/domain/core/entities/core/available_screening_tools.g.dart
test/unit_tests/core/entities/available_screening_tools_test.dart
test/unit_tests/core/entities/screening_tool_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

- fetch list of available screening tools

feat: get a list of available screening tools

---

assets/icons/share_diary_entry_icon.svg
lib/domain/core/value_objects/asset_strings.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart

chore: revamp health diary ui

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart

- fix alignment issue on diary entry page

chore: fix alignment on diary entry page

---

lib/presentation/communities/group_info/widgets/group_member_item.dart

chore: change moderator badge UI

---

lib/application/core/graphql/queries.dart
lib/domain/core/entities/medical_data/medical_data.dart
lib/domain/core/entities/medical_data/medical_data.freezed.dart
lib/domain/core/entities/medical_data/medical_data.g.dart
lib/domain/core/entities/medical_data/medical_data_details.dart
lib/domain/core/entities/medical_data/medical_data_details.freezed.dart
lib/domain/core/entities/medical_data/medical_data_details.g.dart
lib/domain/core/entities/medical_data/medication_codeable_concept.dart
lib/domain/core/entities/medical_data/medication_codeable_concept.freezed.dart
lib/domain/core/entities/medical_data/medication_codeable_concept.g.dart
lib/presentation/profile/medical_data/medical_data_page.dart
test/mocks.dart
test/unit_tests/application/redux/actions/medical_data/fetch_medical_data_action_test.dart
test/unit_tests/domain/core/entities/medical_data/medical_data_details_test.dart
test/widgets_tests/presentation/profile/pages/medical_data_page_test.dart

chore: medical data

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/my_health/fetch_appointments_action.dart
lib/application/redux/actions/my_health/reschedule_appointment_action.dart
lib/domain/core/entities/appointments/appointment.dart
lib/domain/core/entities/appointments/appointment.freezed.dart
lib/domain/core/entities/appointments/appointment.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/my_health/widgets/appointment_list_item.dart
lib/presentation/my_health/widgets/reschedule_appointment_action_dialog.dart
lib/presentation/my_health/widgets/upcoming_appointments.dart
test/mocks.dart
test/unit_tests/core/entities/appointment_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/my_health/appointments_page_test.dart
test/widgets_tests/presentation/my_health/widgets/appointment_list_item_test.dart
test/widgets_tests/presentation/my_health/widgets/reschedule_appointment_action_dialog_test.dart

chore: remove appointment unused fields

---

lib/application/core/graphql/mutations.dart
lib/application/core/graphql/queries.dart
lib/application/redux/actions/communities/share_diary_entry_action.dart
lib/application/redux/actions/share_diary_entry_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/entities/health_diary/health_diary_entry.dart
lib/domain/core/entities/health_diary/health_diary_entry.freezed.dart
lib/domain/core/entities/health_diary/health_diary_entry.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/health_diary/widgets/share_diary_entry_dialog.dart
test/mocks.dart
test/unit_tests/application/redux/actions/share_diary_entry_action_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/health_diary/share_diary_entry_dialog_test.dart

feat: hook up share diary entry to api

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/widgets/screening_tools_question_widget.dart

- fix spacing on screening tools
- fix wording on successful assesment page

feat: fix spacing on screening tools

---

lib/application/redux/actions/screening_tools/answer_screening_tools_action.dart
lib/application/redux/actions/screening_tools/fetch_screening_questions_action.dart
lib/application/redux/flags/flags.dart
lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
test/unit_tests/application/redux/actions/fetch_screening_questions_action_test.dart

- add loading indicators while fetching screening tools from api

chore: add loading indicators while fetching screening tools

---

lib/application/redux/actions/screening_tools/fetch_available_screening_tools_action.dart
lib/presentation/communities/suggested_groups/suggested_groups_section_widget.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tools_carousel.dart

- optimize screening tool fetch login when initializing widget

fix: screening tools

---

lib/application/core/services/utils.dart
lib/application/redux/actions/screening_tools/answer_screening_tools_action.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
test/widgets_tests/presentation/assessment/pages/alcohol_substance_use_page_test.dart
test/widgets_tests/presentation/assessment/pages/contraceptive_assessment_page_test.dart
test/widgets_tests/presentation/assessment/pages/tuberculosis_assessment_page_test.dart
test/widgets_tests/presentation/violence_assessment/violence_assessment_page_test.dart

- prevent users from submitting a screening tools where not all questions are answered

feat: prevent partial submission of screening tools

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/consent/consent_page.dart
test/widgets_tests/presentation/profile/pages/consent_page_test.dart

chore: remove group consent switch

---

lib/application/core/services/utils.dart
lib/presentation/core/widgets/personal_information_secondary_widget.dart
lib/presentation/profile/personal_information/personal_information_page.dart

- refactor personal information page

chore: refactor personal information page

---

lib/application/redux/actions/create_pin_action.dart
test/widgets_tests/presentation/login/create_new_pin_page_test.dart

- navigate dynamically based on state

fix: create PIN

---

lib/application/core/services/app_setup_data.dart
pubspec.lock
pubspec.yaml

- disable expandable question future dates

chore: update afyamojacore version

---

lib/application/redux/actions/communities/accept_decline_communities_invite_action.dart
lib/presentation/communities/invited_groups/pages/accept_group_invites_page.dart
lib/presentation/communities/invited_groups/pages/invited_groups_page.dart
test/mocks.dart
test/widgets_tests/presentation/community/chat_screen/pages/accept_group_invites_page_test.dart
test/widgets_tests/redux/app/actions/accept_decline_communities_invite_action_test.dart

- navigate to communities after accepting group invite

chore: navigate to conversations after accepting group invite

---

lib/application/core/graphql/queries.dart
lib/domain/core/entities/health_diary/health_diary_entry.dart
lib/domain/core/entities/health_diary/health_diary_entry.freezed.dart
lib/domain/core/entities/health_diary/health_diary_entry.g.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart
test/mocks.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

- share recent diary entry once

chore: only share diary entry once

---

lib/application/core/graphql/queries.dart
lib/domain/core/entities/health_diary/health_diary_entry.dart
lib/domain/core/entities/health_diary/health_diary_entry.freezed.dart
lib/domain/core/entities/health_diary/health_diary_entry.g.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart
test/mocks.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

- enable sharing of diary entry after 4 hours

chore: enable sharing of diary entry again

---

lib/application/redux/actions/share_diary_entry_action.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/health_diary/widgets/share_diary_entry_dialog.dart
test/unit_tests/application/redux/actions/share_diary_entry_action_test.dart
test/widgets_tests/presentation/health_diary/share_diary_entry_dialog_test.dart

- add option to share entire health diary

feat: add option to share entire health diary

---

lib/application/redux/actions/onboarding/phone_login_action.dart
lib/presentation/profile/clinic_information/clinic_information_page.dart
lib/presentation/profile/pages/user_profile_page.dart
test/mocks.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/community/chat_screen/pages/accept_group_invites_page_test.dart
test/widgets_tests/presentation/community/chat_screen/pages/invited_groups_page_test.dart
test/widgets_tests/presentation/core/widgets/app_bar/app_bar_user_test.dart
test/widgets_tests/presentation/my_health/my_health_page_test.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

chore: fix error dialog on my health page

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart
test/mocks.dart
test/unit_tests/core/entities/health_diary_state_test.dart
test/widgets_tests/presentation/my_health/my_health_diary_page_test.dart

- display shared diary entry icon

chore: diplay shared diary entry icon

---

lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
lib/presentation/violence_assessment/widgets/screening_tools_question_widget.dart

- fix sizing issues on screening tools

chore: fix spacing issues on screening tools

---

lib/application/redux/actions/set_push_token_action.dart
test/unit_tests/application/redux/actions/set_push_token_action_test.dart

- check login status before setting push token

fix: error dialog on login

---

lib/application/core/services/utils.dart
lib/application/redux/actions/send_feedback_action.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/profile/feedback/feedback_page.dart
lib/presentation/profile/feedback/widgets/rating_button.dart
test/unit_tests/application/redux/actions/send_feedback_action_test.dart
test/widgets_tests/presentation/profile/pages/feedback_page_test.dart

- implement new feedback page UI

feat: implement new feedback page

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/fetch_health_diary_action.dart
lib/application/redux/actions/share_diary_entry_action.dart
lib/presentation/health_diary/pages/my_health_diary_page.dart
lib/presentation/health_diary/widgets/health_diary_entry_widget.dart
lib/presentation/health_diary/widgets/mood_selection/mood_feedback_page.dart

- implement share entire diary entry

chore: implement share entire diary entry

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/feedback/feedback_page.dart

chore: add ratings hint

---

lib/domain/core/entities/health_timeline/fhir_resource.dart
lib/domain/core/entities/health_timeline/fhir_resource.freezed.dart
lib/domain/core/entities/health_timeline/fhir_resource.g.dart
lib/domain/core/entities/health_timeline/reference.dart
lib/domain/core/entities/health_timeline/reference.freezed.dart
lib/domain/core/entities/health_timeline/reference.g.dart
lib/presentation/profile/health_timeline/my_health_timeline.dart
lib/presentation/profile/widgets/dashed_line.dart
test/mocks.dart
test/unit_tests/application/redux/actions/health_timeline/fetch_health_timeline_action_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

fix: timeline values

---

lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/onboarding/set_security_questions/security_questions_page.dart

- add KenyaEMR as a clienr type

fix: login

---

lib/application/redux/actions/health_timeline/fetch_health_timeline_action.dart
lib/domain/core/entities/health_timeline/fhir_enums.dart
lib/presentation/profile/health_timeline/my_health_timeline.dart

Observation categories

---

lib/application/core/graphql/queries.dart
lib/application/core/services/utils.dart
lib/application/redux/actions/profile/fetch_caregiver_information.dart
lib/application/redux/actions/update_client_profile_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/view_models/client_profile_view_model.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/domain/core/entities/profile/caregiver_information.dart
lib/domain/core/entities/profile/caregiver_information.freezed.dart
lib/domain/core/entities/profile/caregiver_information.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/profile/personal_information/personal_information_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
pubspec.lock
pubspec.yaml
test/mocks.dart
test/unit_tests/application/redux/actions/fetch_caregiver_information_test.dart
test/unit_tests/core/entities/profile/caregiver_information_test.dart
test/widgets_tests/presentation/profile/personal_information_page_test.dart

- add caregiver information to state

feat: add care giver information to state

---

lib/presentation/core/widgets/app_bar/custom_app_bar.dart

fix: app bar title wrap

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/my_health/pages/my_health_page.dart
lib/presentation/profile/health_timeline/my_health_timeline.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/my_health/my_health_page_test.dart
test/widgets_tests/presentation/profile/widgets/my_health_timeline_test.dart

feat: health timeline pagination

---

lib/presentation/health_diary/widgets/mood_selection/mood_feedback_page.dart

- add save button for happy diary entries
- request keyboard type without emoji options available

fix: add save button for happy diary entries

---

lib/application/core/graphql/mutations.dart
lib/application/core/services/utils.dart
lib/application/redux/actions/profile/update_caregiver_information_action.dart
lib/domain/core/entities/profile/edit_information_item.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/pages/edit_information_page.dart
lib/presentation/profile/personal_information/personal_information_page.dart
pubspec.lock
test/mocks.dart
test/unit_tests/application/redux/actions/update_caregiver_info_action_test.dart
test/widgets_tests/presentation/profile/widgets/edit_info_button_widget_test.dart

- implement updating of caregiver information

chore: update caregiver information

---

lib/presentation/my_health/pages/my_health_page.dart
lib/presentation/my_health/widgets/profile_health_details_widget.dart
test/widgets_tests/presentation/my_health/my_health_page_test.dart

- organize viral load and next refill cards

fix: vl and next refill

---

lib/application/core/services/utils.dart
lib/presentation/profile/feedback/feedback_page.dart
test/unit_tests/services/utils_test.dart

chore: add snack bar message to feedback page

---

lib/presentation/profile/medical_data/widgets/medical_data_widget.dart

fix: medical data

---

ios/Podfile.lock
lib/presentation/core/widgets/app_bar/app_bar_user.dart
lib/presentation/core/widgets/app_bar/custom_app_bar.dart

fix: update app bar wrapping to ellipsis

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/notifications/fetch_notifications_action.dart
lib/presentation/notifications/notification_list_item.dart
test/mocks.dart

fix: notifications date format

---

lib/presentation/profile/personal_information/personal_information_page.dart

- fix caregiver information navigation
- fix error when updating only one field in caregiver information

fix: navigation for caregiver information

---

lib/presentation/health_diary/widgets/health_diary_entry_widget.dart

- align diary entries to the top

chore: align diary entry items to the top

---

lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/profile/feedback/feedback_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart

refactor: floating buttons

---

lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tool_menu_item.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tools_carousel.dart
lib/presentation/home/pages/home_page.dart
lib/presentation/home/widgets/survey_carousel.dart
test/widgets_tests/presentation/health_diary/screening_tools/widgets/screening_tools_carousel_test.dart
test/widgets_tests/presentation/home/widgets/survey_carousel_test.dart

chore: relocate surveys to home page

---

lib/domain/core/entities/core/content_state.freezed.dart
lib/domain/core/entities/core/content_state.g.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

- fix content engagement state

chore: fix content engagement state

---

README.md
lib/presentation/surveys/surveys_page.dart

chore: update broken surveys link

---

lib/application/core/services/utils.dart
lib/domain/core/entities/core/notification_action_info.dart
lib/domain/core/entities/core/notification_action_info.freezed.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/notifications/notification_list_item.dart
lib/presentation/notifications/notifications_page.dart
pubspec.lock
pubspec.yaml
test/unit_tests/services/utils_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

chore: notifications page redesign

---

lib/presentation/home/pages/home_page.dart

- fix error dialog that occurs on login

fix: fix error dialog on login

---

README.md
lib/domain/core/value_objects/app_strings.dart
lib/presentation/home/widgets/survey_carousel.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
lib/presentation/surveys/custom_webview_page.dart
lib/presentation/surveys/surveys_page.dart
lib/presentation/surveys/widgets/survey_item.dart
pubspec.lock
pubspec.yaml
test/widgets_tests/presentation/home/widgets/survey_carousel_test.dart

- fix survey webview rendering

fix: survey webview rendering

---

lib/presentation/core/theme/theme.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tool_menu_item.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tools_carousel.dart
lib/presentation/home/widgets/survey_carousel.dart

- change survey carousel color scheme

chore: change color scheme on survey carousel

---

lib/application/redux/actions/profile/fetch_caregiver_information.dart
lib/application/redux/actions/update_client_profile_action.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/core/client_state.freezed.dart
lib/domain/core/entities/core/client_state.g.dart
lib/presentation/profile/personal_information/personal_information_page.dart
test/unit_tests/application/redux/actions/fetch_caregiver_information_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/profile/personal_information_page_test.dart

- display personal information only whenit is available

fix: display personal information only when it is available

---

lib/presentation/communities/community_list_page.dart

Fixes connection error on the communities page

fix: communities connection error

---

lib/application/core/graphql/queries.dart
lib/application/redux/actions/surveys/fetch_available_surveys_action.dart
lib/application/redux/actions/update_misc_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/misc_state.dart
lib/application/redux/states/misc_state.freezed.dart
lib/application/redux/states/misc_state.g.dart
lib/domain/core/entities/core/client_state.dart
lib/domain/core/entities/surveys/survey.dart
lib/domain/core/entities/surveys/survey.freezed.dart
lib/domain/core/entities/surveys/survey.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/presentation/home/widgets/survey_carousel.dart
lib/presentation/surveys/surveys_page.dart
lib/presentation/surveys/widgets/survey_item.dart
test/mocks.dart
test/unit_tests/application/redux/actions/fetch_available_surveys_action_test.dart
test/unit_tests/domain/core/entities/surveys/survey_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/surveys/surveys_page_test.dart

feat: fetch available surveys

---

lib/application/core/graphql/mutations.dart
lib/application/redux/actions/send_content_engagement_time_action.dart
lib/application/redux/actions/update_content_engagement_state_action.dart
lib/application/redux/flags/flags.dart
lib/domain/core/entities/feed/content_engagement_state.dart
lib/domain/core/entities/feed/content_engagement_state.freezed.dart
lib/domain/core/entities/feed/content_engagement_state.g.dart
lib/presentation/content/pages/content_details_page.dart
lib/presentation/content/pages/feed_page.dart
pubspec.lock
pubspec.yaml
test/mocks.dart
test/unit_tests/application/redux/actions/send_content_engagement_time_action_test.dart
test/unit_tests/application/redux/actions/update_content_engagement_state_action_test.dart
test/unit_tests/core/entities/content_state_test.dart
test/unit_tests/core/entities/feed/content_engagement_state_test.dart

- add tracking of content view time

feat: add tracking of content view time

---

lib/application/core/services/utils.dart
lib/presentation/core/widgets/preload_app.dart
test/unit_tests/services/utils_test.dart

- prompt resume with pin immediately app life cycle state changes

fix: prompt resume with pin immediately

---

lib/application/core/services/utils.dart
lib/application/redux/actions/resume_with_pin_action/resume_with_pin_action.dart
lib/application/redux/actions/update_misc_state_action.dart
lib/application/redux/states/misc_state.dart
lib/application/redux/states/misc_state.freezed.dart
lib/application/redux/states/misc_state.g.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/onboarding/login/widgets/login_counter_page.dart
lib/presentation/resume_with_pin/resume_with_pin_page.dart
lib/presentation/resume_with_pin/wrong_resume_with_pin_attempts_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
pubspec.lock
pubspec.yaml
test/unit_tests/application/redux/actions/resume_with_pin/resume_with_pin_action_test.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/resume_with_pin/wrong_resume_with_pin_attempts_page_test.dart

- add too many attempts page for resume with pin

feat: add too many attempts page for resume with pin

---

lib/presentation/core/widgets/animated_count.dart
pubspec.lock
pubspec.yaml

chore: reword resend otp timer

---

lib/application/core/graphql/mutations.dart
lib/application/core/graphql/queries.dart
lib/application/redux/actions/surveys/verify_survey_submission_action.dart
lib/application/redux/actions/update_misc_state_action.dart
lib/application/redux/flags/flags.dart
lib/application/redux/states/misc_state.dart
lib/application/redux/states/misc_state.freezed.dart
lib/application/redux/states/misc_state.g.dart
lib/domain/core/entities/surveys/survey.dart
lib/domain/core/entities/surveys/survey.freezed.dart
lib/domain/core/entities/surveys/survey.g.dart
lib/presentation/home/widgets/survey_carousel.dart
lib/presentation/surveys/custom_webview_page.dart
lib/presentation/surveys/widgets/custom_webview_back_button.dart
pubspec.lock
test/unit_tests/application/redux/actions/verify_survey_submission_action_test.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/home/widgets/survey_carousel_test.dart

- verify survey submission upon exiting survey webview

feat: verify survey submission upon exiting survey webview

---

lib/domain/core/entities/surveys/survey.dart
lib/domain/core/entities/surveys/survey.freezed.dart
lib/domain/core/entities/surveys/survey.g.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart

fix: fix surveys serialization

---

lib/presentation/onboarding/login/pages/login_page.dart

feat: version number in login page

---

lib/domain/core/entities/core/helpline.dart
lib/domain/core/value_objects/app_strings.dart
lib/domain/core/value_objects/app_widget_keys.dart
lib/presentation/profile/hotline/pages/hotlines_page.dart
lib/presentation/profile/hotline/widgets/helpline_items_widget.dart
lib/presentation/profile/hotline/widgets/hotline_widget.dart
lib/presentation/profile/pages/user_profile_page.dart
lib/presentation/router/router_generator.dart
lib/presentation/router/routes.dart
test/unit_tests/router/router_generator_test.dart
test/widgets_tests/presentation/profile/hotline/pages/hotlines_page_test.dart
test/widgets_tests/presentation/profile/hotline/widgets/helpline_items_widget_test.dart
test/widgets_tests/presentation/profile/pages/user_profile_page_test.dart

- setup helpline data
- add helpline widgets

feat: add more helplines on the app

---

lib/application/redux/actions/security_questions/record_security_question_responses_action.dart
lib/presentation/onboarding/set_security_questions/security_questions_page.dart

chore: fix answering of security questions

---

test/mocks.dart
test/unit_tests/services/analytics_service_test.dart
test/unit_tests/services/utils_test.dart

- extract analytics service tests

test: add analytics service tests

---

lib/presentation/profile/faqs/profile_faqs_page.dart

fix: FAQs page scrolling

---

lib/application/core/graphql/mutations.dart
lib/application/core/services/analytics_service.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/send_content_engagement_time_action.dart
lib/application/redux/actions/update_content_like_status_action.dart
lib/domain/core/value_objects/app_events.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/content/pages/content_details_page.dart
lib/presentation/content/pages/feed_page.dart
lib/presentation/content/widgets/feed_categories_widget.dart
lib/presentation/content/widgets/recent_content_widget.dart
lib/presentation/onboarding/login/pages/login_page.dart
lib/presentation/router/router_generator.dart
test/mocks.dart
test/unit_tests/application/redux/actions/send_content_engagement_time_action_test.dart
test/unit_tests/router/router_generator_test.dart
test/unit_tests/services/analytics_service_test.dart
test/widgets_tests/presentation/feed/widgets/feed_page_content_item_test.dart
test/widgets_tests/presentation/login/login_page_test.dart
test/widgets_tests/presentation/login/set_nickname_page_test.dart
test/widgets_tests/presentation/notifications/notifications_page_test.dart
test/widgets_tests/presentation/profile/pages/profile_faqs/profile_faqs_page_test.dart

- add content view event
- add content interaction time event
- add content view all event

feat: add more events

---

lib/application/redux/actions/screening_tools/answer_screening_tools_action.dart
lib/domain/core/value_objects/app_events.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/core/widgets/custom_back_button.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tool_menu_item.dart
lib/presentation/health_diary/screening_tools/widgets/screening_tools_carousel.dart
lib/presentation/home/widgets/survey_carousel.dart
lib/presentation/surveys/custom_webview_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart
test/widgets_tests/presentation/assessment/pages/alcohol_substance_use_page_test.dart
test/widgets_tests/presentation/assessment/pages/contraceptive_assessment_page_test.dart
test/widgets_tests/presentation/assessment/pages/tuberculosis_assessment_page_test.dart
test/widgets_tests/presentation/health_diary/screening_tools/widgets/screening_tools_carousel_test.dart
test/widgets_tests/presentation/violence_assessment/violence_assessment_page_test.dart

- add event logging to screening tools
- log abandon events to log when screening tools are abandoned

feat: add event logging on screening tools

---

lib/domain/core/value_objects/app_events.dart
lib/presentation/home/widgets/survey_carousel.dart
test/widgets_tests/presentation/home/widgets/survey_carousel_test.dart

chore: add event for viewing surveys

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/home/widgets/survey_carousel.dart
lib/presentation/profile/feedback/feedback_page.dart

- change feedback title
- fix event title for surveys
- fix title casing on personal information page

chore: change feedback wording

---

lib/application/core/services/onboarding_utils.dart
lib/application/redux/actions/accept_terms_and_conditions_action.dart
lib/application/redux/actions/create_pin_action.dart
lib/application/redux/actions/security_questions/record_security_question_responses_action.dart
lib/application/redux/actions/security_questions/verify_security_questions_action.dart
lib/application/redux/actions/set_nickname_action.dart
lib/application/redux/actions/verify_otp_action.dart
lib/domain/core/value_objects/app_events.dart
lib/domain/core/value_objects/enums.dart
lib/presentation/onboarding/set_nickname/pages/set_nickname_page.dart
lib/presentation/onboarding/terms/terms_and_conditions_page.dart
lib/presentation/onboarding/verify_phone/pages/verify_phone_page.dart
test/mocks.dart
test/unit_tests/application/redux/actions/onboarding/set_nickname_action_test.dart
test/widgets_tests/presentation/login/create_new_pin_page_test.dart
test/widgets_tests/presentation/onboarding/login/pages/verify_phone_page_test.dart
test/widgets_tests/presentation/onboarding/login/widgets/verify_otp_widget_test.dart
test/widgets_tests/presentation/onboarding/pin_expired/pages/pin_expired_page_test.dart
test/widgets_tests/presentation/onboarding/security_questions/forgot_pin_page_test.dart
test/widgets_tests/presentation/onboarding/security_questions/security_questions_page_test.dart
test/widgets_tests/presentation/onboarding/terms_and_conditions_page_test.dart
test/widgets_tests/redux/actions/onboarding/login/create_pin_action_test.dart
test/widgets_tests/redux/actions/onboarding/security_questions/verify_security_questions_action_test.dart

- add verify phone events
- add security questions events
- add terms and conditions events
- add send and resend OTP events
- add verify OTP events with next route

feat: add onboarding events

---

lib/application/redux/actions/create_health_diary_action.dart
lib/application/redux/actions/create_pin_action.dart
lib/application/redux/actions/onboarding/phone_login_action.dart
lib/application/redux/actions/onboarding/pin_reset_service_request_action.dart
lib/application/redux/actions/set_nickname_action.dart
lib/domain/core/entities/appointments/appointments_state.freezed.dart
lib/domain/core/entities/appointments/appointments_state.g.dart
lib/domain/core/value_objects/app_events.dart
test/widgets_tests/application/core/custom_client_test.mocks.dart
test/widgets_tests/presentation/onboarding/security_questions/verify_security_questions_help_page_test.dart

- record the text when recording diary entries
- add reset PIN events by client
- add PIN reset service request events

feat: add more onboarding events

---

lib/presentation/profile/pages/edit_information_page.dart

- change phone number text input type to numerical for caregiver information page

chore: change text input type for caregiver information

---

lib/application/redux/view_models/groups/groups_view_model.dart
lib/presentation/communities/group_info/pages/group_info_page.dart
lib/presentation/communities/group_info/pages/group_member_connector.dart

- User unable to perform moderation actions on their own account
- Default user type in community if absent

feat: default user type name

---

lib/domain/core/value_objects/app_strings.dart

fix: moderation dialog text overflow

---

lib/presentation/core/widgets/preload_app.dart

chore: fix connectivity checker

---

lib/presentation/communities/community_list_page.dart

- fix empty conversations widget

chore: fix empty conversations widget

---

lib/presentation/assessment/pages/alcohol_substance_use_page.dart
lib/presentation/assessment/pages/contraceptive_assessment_page.dart
lib/presentation/assessment/pages/tuberculosis_assessment_page.dart
lib/presentation/violence_assessment/pages/violence_assessment_page.dart

- fix screening tools bottom spacing

chore: fix screening tools bottom spacing

---

lib/presentation/surveys/surveys_page.dart

fix: surveys page overflow and scrolling

---

lib/presentation/home/pages/home_page.dart

fix: home page scrolling

---

lib/presentation/core/widgets/app_bar/app_bar_user.dart

chore: update user icon background color

---

pubspec.lock
pubspec.yaml

fix: notifications

---

lib/domain/core/value_objects/app_strings.dart
lib/presentation/profile/hotline/widgets/hotline_widget.dart

- display hotline facility container even when facility number does not exist

feat: display hotline facility container

---

.circleci/config.yml
.github/workflows/config.yaml
lib/application/redux/actions/communities/fetch_group_members_action.dart
lib/presentation/communities/channel_page.dart
lib/presentation/communities/chat_screen/widgets/chat_page_app_bar.dart

Fix chat count

---

pubspec.lock
pubspec.yaml

- update afya moja core
Signed-off-by: Byron Kimani <byronkimani@Byrons-MacBook-Pro.local>

chore: update afya_moja_core
